### ISSUE TITLE
MobileRoad requires registration now

### ISSUE THREAD

**Issue by mjsmith** [alpha-beta-soup/mobile-road-extraction#8]
The code fails as you must now enter an email address prior to accessing. Can we enter a cookie in the code somewhere to make this work?

**Comment by alpha-beta-soup** [comment]
Yep, I'm happy to look into this. Of course now that you must register, it's important to consider the terms of the agreement. In particular:

> You agree not to not copy, decompile, modify, reverse engineer, re-publish or create derivative works out of any Information, Functionality or Service without the disclosing party's written consent.

I figure as long as you use this for personal reasons and not as part of a commercial activity or for redistribution, then it's above water. I will not publish any more updates to the data in this repo (but will leave the means for individuals to extract it for themselves).

**Comment by mjsmith** [comment]
Cool, thanks. I might send them a note and see why we can't use the data for other purposes, since it's just a handy dataset.

**Comment by alpha-beta-soup** [comment]
Actually, it was just missing a header that triggered a Server Error if absent. Fixed now.
